/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DepositRouteImport } from './routes/deposit'
import { Route as ClassifiedAdsIndexRouteImport } from './routes/classified-ads/index'
import { Route as ClassifiedAdsIdIndexRouteImport } from './routes/classified-ads/$id/index'
import { Route as ClassifiedAdsIdDeleteRouteImport } from './routes/classified-ads/$id/delete'
import { Route as ClassifiedAdsIdOfferRouteImport } from './routes/classified-ads/$id/offer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositRoute = DepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassifiedAdsIndexRoute = ClassifiedAdsIndexRouteImport.update({
  id: '/classified-ads/',
  path: '/classified-ads/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassifiedAdsIdIndexRoute = ClassifiedAdsIdIndexRouteImport.update({
  id: '/classified-ads/$id/',
  path: '/classified-ads/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassifiedAdsIdDeleteRoute = ClassifiedAdsIdDeleteRouteImport.update({
  id: '/classified-ads/$id/delete',
  path: '/classified-ads/$id/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassifiedAdsIdOfferRoute = ClassifiedAdsIdOfferRouteImport.update({
  id: '/classified-ads/$id/offer',
  path: '/classified-ads/$id/offer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deposit': typeof DepositRoute
  '/classified-ads/': typeof ClassifiedAdsIndexRoute
  '/classified-ads/$id/delete': typeof ClassifiedAdsIdDeleteRoute
  '/classified-ads/$id/offer': typeof ClassifiedAdsIdOfferRoute
  '/classified-ads/$id/': typeof ClassifiedAdsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deposit': typeof DepositRoute
  '/classified-ads': typeof ClassifiedAdsIndexRoute
  '/classified-ads/$id/delete': typeof ClassifiedAdsIdDeleteRoute
  '/classified-ads/$id/offer': typeof ClassifiedAdsIdOfferRoute
  '/classified-ads/$id': typeof ClassifiedAdsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deposit': typeof DepositRoute
  '/classified-ads/': typeof ClassifiedAdsIndexRoute
  '/classified-ads/$id/delete': typeof ClassifiedAdsIdDeleteRoute
  '/classified-ads/$id/offer': typeof ClassifiedAdsIdOfferRoute
  '/classified-ads/$id/': typeof ClassifiedAdsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deposit'
    | '/classified-ads/'
    | '/classified-ads/$id/delete'
    | '/classified-ads/$id/offer'
    | '/classified-ads/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deposit'
    | '/classified-ads'
    | '/classified-ads/$id/delete'
    | '/classified-ads/$id/offer'
    | '/classified-ads/$id'
  id:
    | '__root__'
    | '/'
    | '/deposit'
    | '/classified-ads/'
    | '/classified-ads/$id/delete'
    | '/classified-ads/$id/offer'
    | '/classified-ads/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DepositRoute: typeof DepositRoute
  ClassifiedAdsIndexRoute: typeof ClassifiedAdsIndexRoute
  ClassifiedAdsIdDeleteRoute: typeof ClassifiedAdsIdDeleteRoute
  ClassifiedAdsIdOfferRoute: typeof ClassifiedAdsIdOfferRoute
  ClassifiedAdsIdIndexRoute: typeof ClassifiedAdsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit': {
      id: '/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof DepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classified-ads/': {
      id: '/classified-ads/'
      path: '/classified-ads'
      fullPath: '/classified-ads/'
      preLoaderRoute: typeof ClassifiedAdsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classified-ads/$id/': {
      id: '/classified-ads/$id/'
      path: '/classified-ads/$id'
      fullPath: '/classified-ads/$id/'
      preLoaderRoute: typeof ClassifiedAdsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classified-ads/$id/delete': {
      id: '/classified-ads/$id/delete'
      path: '/classified-ads/$id/delete'
      fullPath: '/classified-ads/$id/delete'
      preLoaderRoute: typeof ClassifiedAdsIdDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classified-ads/$id/offer': {
      id: '/classified-ads/$id/offer'
      path: '/classified-ads/$id/offer'
      fullPath: '/classified-ads/$id/offer'
      preLoaderRoute: typeof ClassifiedAdsIdOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DepositRoute: DepositRoute,
  ClassifiedAdsIndexRoute: ClassifiedAdsIndexRoute,
  ClassifiedAdsIdDeleteRoute: ClassifiedAdsIdDeleteRoute,
  ClassifiedAdsIdOfferRoute: ClassifiedAdsIdOfferRoute,
  ClassifiedAdsIdIndexRoute: ClassifiedAdsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
